version: '3'
services:
  pg:
    image: postgres
    restart: always
    volumes:
      - ./postgress-data:/var/lib/postresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: extremaly
  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
